educationKeywords = [
    "escola",
    "universidade",
    "faculdade",
    "colégio",
    "cursinho",
    "ensino médio",
    "ensino fundamental",
    "graduação",
    "pós-graduação",
    "mestrado",
    "doutorado",
    "livro",
    "material escolar",
    "caderno",
    "caneta",
    "borracha",
    "régua",
    "dicionário",
    "atlas",
    "giz",
    "lápis",
    "lousa",
    "quadro-negro",
    "laptop",
    "computador",
    "impressora",
    "estudar",
    "mensalidade",
]
