healthcareKeywords = [
    "tratamento médico",
    "médico",
    "receita",
    "consulta",
    "exame",
    "teste",
    "vacina",
    "medicamento",
    "remédio",
    "analgésico",
    "antibiótico",
    "antidepressivo",
    "antipirético",
    "antialérgico",
    "anti inflamatório",
    "dentista",
    "ortodontista",
    "odontologia",
    "procedimento",
    "cirurgia",
    "hospital",
    "enfermaria",
    "UTI",
    "internação",
    "consultório",
    "clínica",
    "ambulatório",
    "plano de saúde",
    "seguro",
    "convênio",
    "reembolso",
    "receita médica",
    "receita controlada",
    "receita branca",
    "receita vermelha"
]
