housingKeywords = [
    "aluguel",
    "hipoteca",
    "aluguer",
    "imposto de propriedade",
    "condomínio",
    "IPTU",
    "energia elétrica",
    "gás",
    "água",
    "telefone",
    "internet",
    "TV a cabo",
    "concerto",
    "parede",
    "limpeza",
    "pintura",
    "reforma",
    "conserto",
    "manutenção",
    "móveis",
    "eletrodomésticos",
    "decoração",
    "tapete",
    "cortina",
    "lâmpada",
    "sofá",
    "cadeira",
    "mesa",
    "cama",
    "armário",
    "guarda-roupa",
    "estante",
    "prateleira",
    "caixa de ferramentas",
    "máquina de lavar",
    "fogão",
    "geladeira",
    "microondas",
    "aspirador de pó",
    "ferro de passar",
    "tábua de passar",
    "esfregão",
    "vassoura",
    "pá",
    "rodo"
]