selfCareKeywords = [
    "corte de cabelo",
    "beleza",
    "academia",
    "ginástica",
    "esporte",
    "musculação",
    "natação",
    "caminhada",
    "corrida",
    "ciclismo",
    "yoga",
    "pilates",
    "danca",
    "boxing",
    "kickboxing",
    "muay thai",
    "jiu jitsu",
    "judô",
    "karate",
    "taekwondo",
    "artes marciais",
    "massagem",
    "estética",
    "manicure",
    "pedicure",
    "maquiagem",
    "perfume",
    "barbearia",
    "cabeleireiro",
    "salão de beleza",
    "spa",
    "academia de ginástica",
    "clube esportivo",
    "sala de musculação",
    "piscina",
    "pista de atletismo",
    "centro de yoga",
    "estúdio de pilates",
    "escola de dança",
    "boxe",
    "kickboxing",
    "muay thai",
    "jiu jitsu",
    "judô",
    "karate",
    "taekwondo",
    "artes marciais",
    "clínica de massagem",
    "salão de estética",
    "salão de manicure e pedicure",
    "loja de maquiagem",
    "loja de perfumes",
    "barbearia",
    "cabeleireiro",
    "salão de beleza",
    "spa"
]
