transportationKeywords = [
    "carro",
    "gasolina",
    "ônibus",
    "táxi",
    "uber",
    "oficina"
    "carro",
    "gasolina",
    "transporte público",
    "táxi",
    "ônibus",
    "metrô",
    "trem",
    "bonde",
    "van",
    "furgão",
    "caminhão",
    "moto",
    "bicicleta",
    "aluguel de carro",
    "seguro de carro",
    "licenciamento",
    "IPVA",
    "manutenção",
    "reparo",
    "pneu",
    "freio",
    "suspensão",
    "direção",
    "mecânico",
    "oficina",
    "combustível",
    "posto de gasolina",
    "estacionamento",
    "pedágio",
    "bilhete de ônibus",
    "bilhete de metrô",
    "bilhete de trem",
    "bilhete de bonde",
    "cartão de transporte público",
    "tarifa de táxi",
    "tarifa de van",
    "tarifa de furgão",
    "tarifa de caminhão",
    "seguro de moto",
    "acessórios para bicicleta",
    "acessórios para carro",
    "acessórios para moto"
]