travelKeywords = [
    "viagem",
    "passagem",
    "avião",
    "viagem",
    "tarifa aérea",
    "hotel",
    "tour",
    "passagem de avião",
    "reserva de hotel",
    "passeio turístico",
    "aluguel de carro",
    "seguro de viagem",
    "intercâmbio",
    "cruzeiro",
    "louge",
    "bagagem",
    "passaporte",
    "visto",
    "vaccinação",
    "exame médico",
    "despesas de viagem",
    "moeda estrangeira",
    "dinheiro",
    "cartão de crédito",
    "cheque de viagem",
    "vacinação",
    "seguro de saúde",
    "seguro de viagem",
    "agência de viagem",
    "operadora de turismo",
    "consulado",
    "embaixada",
    "aeroporto",
    "rodoviária",
    "estacionamento do aeroporto",
    "estacionamento da rodoviária",
    "passagem de ônibus",
    "passagem de trem",
    "passagem de navio",
    "passagem de metrô",
    "bilhete de avião",
    "bilhete de ônibus",
    "bilhete de trem",
    "bilhete de navio",
    "bilhete de metrô"
]